pinecone-studio/pinecone-intern-monorepo-2

- apps/1CD/instagram/backend/src/resolvers/mutations/auth/verify-newpass.ts
- apps/1CD/instagram/backend/src/schemas/user.schema.ts
forget password bolon verify passwordiinn zuvhun backendiig zasvarlav
> forget pass and verify pass iin backendiig zasvarlav

- apps/1CD/instagram/backend/src/resolvers/mutations/comment/create-comment.ts
bagshiin uurchlultiiig oruulsan
> fix(backend): bagshiin uurchlultiig oruulsan

- apps/1CD/hotel-booking/frontend/cypress/e2e/(public)/HomePage.cy.tsx
- apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
> feat(hotel-booking frontend): homePage Cypress hiij uzev

- apps/1CD/instagram/backend/src/schemas/user.schema.ts
> fix(backedn): schema deer yum uurchilsun

- apps/1CD/hotel-booking/frontend/src/app/(client)/page.tsx
hotel-booking frontend hotel deer darhad hotelDetails ruu usrene & ID ugsun
> feat(hotel-booking): hotel-booking frontend

- apps/1CD/hotel-booking/frontend/cypress/utils/all-pages.json
- apps/1CD/hotel-booking/frontend/src/app/(admin)/add-hotel/home-page/page.tsx
- apps/1CD/hotel-booking/frontend/src/app/(admin)/layout.tsx
- apps/1CD/hotel-booking/frontend/src/app/layout.tsx
- apps/1CD/hotel-booking/frontend/src/components/providers/Sidebar.tsx
- apps/1CD/hotel-booking/frontend/src/components/providers/index.ts
> feat(hotel-booking): hotel-booking-frontend

- apps/1CD/leave-request/frontend/src/components/providers/ApolloWrapper.tsx
Frontend-н .env холбох холбоосыг өөрчилсөн.
> edit env connection

- apps/1CD/concert-ticket-booking/backend/next.config.js
secret manager /frontend-development(delete BACKEND_URI)/
changed secret-manager
> [concert] docs: changed secret-manager and next config

- apps/1CD/instagram/backend/src/utils/sendmail.ts
> fix(backend): send email

- apps/1CD/instagram/frontend/src/components/header/UserBar.tsx
- apps/1CD/instagram/frontend/src/components/post/CreatePost.tsx
- apps/1CD/instagram/frontend/src/components/post/PostCard.tsx
> change icon

- apps/1CD/hotel-booking/backend/specs/resolvers/queries/bookings/get-booking-find-by-user-id.spec.ts
- apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/get-user-find-by-id.ts
- apps/1CD/hotel-booking/backend/src/resolvers/queries/bookings/index.ts
- apps/1CD/hotel-booking/backend/src/schemas/booking.schema.ts
> feat(hotel-booking-backend): hb-backend getbookings with jest test

- apps/1CD/instagram/frontend/project.json
> feat(fe): project json

- apps/1CD/leave-request/frontend/cypress/utils/all-pages.json
- apps/1CD/leave-request/frontend/src/components/admin/CreateEmployeeModal.tsx
- apps/1CD/leave-request/frontend/src/graphql/all.graphql
Шинэ ажилтан нэмэх modal хийлээ. Тест одоогоор бичээгүй.
> Create employee without test

- apps/1CD/instagram/backend/specs/resolvers/queries/post/get-post.spec.ts
- apps/1CD/instagram/backend/src/resolvers/mutations/comment/index.ts
- apps/1CD/instagram/backend/src/resolvers/mutations/index.ts
- apps/1CD/instagram/backend/src/resolvers/queries/post/get-post.ts
- apps/1CD/instagram/backend/src/resolvers/queries/post/index.ts
- apps/1CD/instagram/backend/src/schemas/post.schema.ts
- apps/1CD/instagram/frontend/project.json
> 650 get post backend

- apps/1CD/instagram/frontend/cypress/e2e/(main)/userName.cy.tsx
- apps/1CD/instagram/frontend/specs/components/user-profile/ChangeProImg.spec.tsx
- apps/1CD/instagram/frontend/specs/components/user-profile/NoPost.spec.tsx
- apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
- apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
- apps/1CD/instagram/frontend/src/components/user-profile/ChangeProImg.tsx
- apps/1CD/instagram/frontend/src/components/user-profile/NoPost.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
user profiliin zurag solih heseg done. odoo postuud harah hesgiig hiine
> 612 ig fe user profiliin zurag solih angid

- apps/1CD/instagram/frontend/cypress/e2e/id.cy.tsx
- apps/1CD/instagram/frontend/cypress/utils/all-pages.json
- apps/1CD/instagram/frontend/src/app/(main)/_components/SearchComponent.tsx
- apps/1CD/instagram/frontend/src/app/home/viewprofile/[id]/page.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
> visit profile page  frontend

- apps/1CD/leave-request/backend/specs/resolvers/mutations/request/update-request.spec.ts
- apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-all-requests-by-supervisor.spec.ts
- apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-request-by-id.spec.ts
- apps/1CD/leave-request/backend/src/resolvers/mutations/request/index.ts
- apps/1CD/leave-request/backend/src/resolvers/mutations/request/update-request.ts
- apps/1CD/leave-request/backend/src/resolvers/queries/request/get-request-by-id.ts
- apps/1CD/leave-request/backend/src/resolvers/queries/request/get-requests.ts
- apps/1CD/leave-request/backend/src/resolvers/queries/request/index.ts
- apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Supervisor backend болон test нэмлээ.
> leave-req supervisor back-test

- apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
- apps/1CD/instagram/frontend/src/components/providers/AuthProvider.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
odoo ghde nemj zasna. hervee follower esvel following bhgui ued 0 haragddag bolgoj zasna. Bas page dotorhoo component bolgoj zadlah. suman functionuudaa inline bolgoj zasna.
> 743 ig fe user profile iin follower following iig follow modeloos avcg zasah

- apps/1CD/instagram/frontend/cypress/e2e/id.cy.tsx
- apps/1CD/instagram/frontend/specs/components/visit-profile/HeadingSection.spec.tsx
- apps/1CD/instagram/frontend/src/app/home/viewprofile/[id]/page.tsx
- apps/1CD/instagram/frontend/src/components/providers/UserProvider.tsx
- apps/1CD/instagram/frontend/src/components/visit-profile/HeadingSection.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
> send follow request from profile page

- apps/1CD/leave-request/frontend/cypress/e2e/(main)/(main)/create-request.cy.tsx
- apps/1CD/leave-request/frontend/src/app/admin/page.tsx
- apps/1CD/leave-request/frontend/src/components/admin/EmployeeList.tsx
- apps/1CD/leave-request/frontend/src/components/admin/Table.tsx
- apps/1CD/leave-request/frontend/src/components/admin/TableStatic.tsx
> Update Admin table

- apps/1CD/instagram/frontend/cypress/e2e/(main)/userName.cy.tsx
- apps/1CD/instagram/frontend/specs/components/user-profile/FollowingDialog.spec.tsx
- apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
- apps/1CD/instagram/frontend/src/components/user-profile/FollowingDialog.tsx
> feat(fe): following dialog

- apps/1CD/concert-ticket-booking/backend/specs/resolvers/mutations/event/update-event-priority.spec.ts
- apps/1CD/concert-ticket-booking/backend/src/resolvers/mutations/event/update-event-priority.ts
- apps/1CD/concert-ticket-booking/backend/src/schemas/event.schema.ts
> feat: (concert-backend) : Admintable-specialButton 

- apps/1CD/instagram/frontend/cypress/e2e/(main)/userName.cy.tsx
- apps/1CD/instagram/frontend/specs/components/user-profile/FollowingDialog.spec.tsx
- apps/1CD/instagram/frontend/specs/components/visit-profile/PostsSection.spec.tsx
- apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
- apps/1CD/instagram/frontend/src/app/home/viewprofile/[id]/page.tsx
- apps/1CD/instagram/frontend/src/components/visit-profile/PostsSection.tsx
- apps/1CD/instagram/frontend/src/graphql/Post.graphql
> get posts on user's profile page

- apps/1CD/leave-request/frontend/src/components/admin/TableStatic.tsx
- apps/1CD/leave-request/frontend/src/graphql/all.graphql
> Role checkbox updated

- apps/1CD/tinder/backend/specs/resolvers/mutations/swipe/match.spec.ts
- apps/1CD/tinder/backend/src/resolvers/queries/swipe/index.ts
- apps/1CD/tinder/backend/src/resolvers/queries/swipe/match.ts
- apps/1CD/tinder/backend/src/schemas/swipe/swipe.schema.ts
done backend of get user of match
> feat: tinder:done backend get user 

- apps/1CD/instagram/frontend/specs/components/story/CreateStory.spec.tsx
- apps/1CD/instagram/frontend/specs/components/story/DiscardStory.spec.tsx
- apps/1CD/instagram/frontend/specs/components/visit-profile/HeadingSection.spec.tsx
- apps/1CD/instagram/frontend/src/app/(main)/_components/Header.tsx
- apps/1CD/instagram/frontend/src/components/story/CreateStory.tsx
- apps/1CD/instagram/frontend/src/components/story/DiscardStory.tsx
- apps/1CD/instagram/frontend/src/graphql/story.graphql
> create story frontend

- apps/1CD/tinder/backend/src/schemas/swipe/swipe.schema.ts
> feat: tinder

- apps/1CD/instagram/backend/specs/resolvers/mutations/follow/send-follow-req.spec.ts
- apps/1CD/instagram/backend/src/resolvers/mutations/follow/send-follow-req.ts
> feat(be): folloew request ilgeehed davhar notification uusne

- apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-all-request-length.spec.ts
- apps/1CD/leave-request/backend/specs/resolvers/queries/request/get-request-length-with-group.spec.ts
- apps/1CD/leave-request/backend/src/resolvers/queries/request/get-all-reqeust-length.ts
- apps/1CD/leave-request/backend/src/schemas/request.schema.ts
Backend: add filter on request length
> 1199 leave request request length filter

- apps/1CD/leave-request/frontend/src/components/supervisor/RequestCategory.tsx
> request length front

- apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyFollowReqCard.tsx
- apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyPostLikeCard.tsx
- apps/1CD/instagram/frontend/src/app/(main)/_components/notification/index.tsx
- apps/1CD/instagram/frontend/src/app/home/[user.userName]/page.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
> 1313 ig fe notification sortloh bolon viewed iin bg tsagaan boloh

- apps/1CD/instagram/frontend/src/app/(main)/_components/NotifyFollowReqCard.tsx
- apps/1CD/instagram/frontend/src/app/(main)/_components/notification/index.tsx
- apps/1CD/instagram/frontend/src/graphql/all.graphql
> 1334 ig fe notificationaas confirm hiih

- apps/1CD/instagram/backend/specs/resolvers/queries/follow/get-follow-status-by-following-id-query..spec.ts
- apps/1CD/instagram/backend/src/resolvers/queries/follow/get-follow-status-by-following-id-query.ts
- apps/1CD/instagram/backend/src/schemas/follow.schema.ts
get follow status by following ID followingid ni userId bolno
> get follow status by following id

- apps/1CD/concert-ticket-booking/backend/src/resolvers/queries/event/get-events-pagination.ts
- apps/1CD/concert-ticket-booking/frontend/src/app/admin/cancel-request/page.tsx
> feat: finish

- apps/2CD/hotel/backend/src/models/room-schema.ts
- apps/2CD/hotel/backend/src/models/room-service-schema.ts
add room schema and room service schema
> feat(hotel): add room schema and room service schema

- apps/2CD/tinder/backend/specs/resolvers/mutations/like/create-like.spec.ts
- apps/2CD/tinder/backend/specs/resolvers/queries/like/get-likes-from-user.spec.ts
- apps/2CD/tinder/backend/specs/resolvers/queries/like/get-likes-to-user.spec.ts
- apps/2CD/tinder/backend/src/models/like.ts
- apps/2CD/tinder/backend/src/resolvers/index.ts
- apps/2CD/tinder/backend/src/resolvers/mutations/like/create-like.ts
- apps/2CD/tinder/backend/src/resolvers/queries/like/get-likes-from-user.ts
- apps/2CD/tinder/backend/src/resolvers/queries/like/get-likes-to-user.ts
- apps/2CD/tinder/backend/src/schemas/index.ts
- apps/2CD/tinder/backend/src/schemas/like.schema.ts
- apps/2CD/tinder/backend/tsconfig.json
> feat(backend): like resolver with jest test

- .gitignore
- apps/2CD/hotel/backend/specs/resolvers/mutations/add-hotel.spec.ts
- apps/2CD/hotel/backend/specs/resolvers/queries/get-all-hotels.spec.ts
- apps/2CD/hotel/backend/src/models/room-schema.ts
- apps/2CD/hotel/backend/src/models/room-service-schema.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/mutations/add-hotel.ts
- apps/2CD/hotel/backend/src/resolvers/queries/get-all-hotels.ts
- apps/2CD/hotel/backend/src/schemas/common.schema.ts
- apps/2CD/hotel/backend/src/types/room-types.ts
- apps/2CD/hotel/backend/src/utils/connect-to-db.ts
made example hotel mutation and query and fixed lint errors
> feat: fixed lint

- apps/2CD/hotel/backend/specs/resolvers/mutations/create-room.spec.ts
- apps/2CD/hotel/backend/src/models/hotel.ts
- apps/2CD/hotel/backend/src/models/room.model.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/mutations/room/create-room.ts
- apps/2CD/hotel/backend/src/schemas/room.schema.ts
1.write createroom test
2.fix createRoom mutation
> feat(hotel): write createroom test

- apps/2CD/tinder/backend/specs/resolvers/mutations/like/create-like.spec.ts
- apps/2CD/tinder/backend/src/resolvers/mutations/like/create-like.ts
> feat: create message

- apps/2CD/tinder/backend/specs/resolvers/mutations/user/login.spec.ts
- apps/2CD/tinder/backend/src/resolvers/mutations/user/login.ts
- apps/2CD/tinder/backend/src/resolvers/mutations/user/register-user.ts
- apps/2CD/tinder/backend/src/resolvers/mutations/user/update-user.ts
User Mutation fixes
- Login
- UpdateUser
- RegisterUser
- login.spec.ts
> fix: [fix] user mutation fixes

- apps/2CD/hotel/backend/specs/resolvers/mutations/delete-room.spec.ts
- apps/2CD/hotel/backend/specs/resolvers/mutations/update-room.spec.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/mutations/room/delete-room.ts
- apps/2CD/hotel/backend/src/resolvers/mutations/room/update-room.ts
- apps/2CD/hotel/backend/src/schemas/room.schema.ts
1.add delete room mutation 
2. add update room mutation 
3. delete-room test 
4. update-room test
> feat(hotel): write delete room and update room

- apps/2CD/restaurant/backend/specs/resolvers/mutations/userRelatedMutations/loginUser.spec.ts
- apps/2CD/restaurant/backend/specs/resolvers/mutations/userRelatedMutations/userHelpers.spec.ts
- apps/2CD/restaurant/backend/src/models/user.model.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/foodRelatedMutations/create-food.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/index.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/userRelatedMutations/create-user.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/userRelatedMutations/user-helpers.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/userRelatedMutations/user-login.ts
- apps/2CD/restaurant/backend/src/schemas/user.schema.ts
-bcrypt password compare
-generate token jwt
> feat(restaurant backend): user login

- apps/2CD/hotel/backend/specs/resolvers/mutations/review-mutations.spec.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/mutations/review-mutations.ts
- apps/2CD/hotel/backend/src/schemas/index.ts
- apps/2CD/hotel/backend/src/schemas/review-schema.ts
- apps/2CD/hotel/backend/src/schemas/user-schema.ts
1.created review schema
2. created review mutations (create and update)
> feat(created-hotel-review-mutation): created hotel mutation and schema

- apps/2CD/restaurant/backend/specs/resolvers/mutations/userRelatedMutations/changePassword.spec.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/index.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/userRelatedMutations/change-password.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/userRelatedMutations/user-login.ts
- apps/2CD/restaurant/backend/src/schemas/user.schema.ts
now user can change password if user knows the current password
> feat(restaurant backend): change user password

- apps/2CD/hotel/backend/specs/resolvers/queries/reviews/review-query.spec.ts
- apps/2CD/hotel/backend/src/models/review.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/queries/review-query.ts
- apps/2CD/hotel/backend/src/types/review.ts
1. created review query
2. fix review model
3. review query type added
> feat(added review): added review query and small model change

- apps/2CD/concert/backend/specs/resolvers/mutations/request/update-req.spec.ts
- apps/2CD/concert/backend/specs/resolvers/mutations/user/update-pass.spec.ts
- apps/2CD/concert/backend/specs/resolvers/mutations/user/update-user.spec.ts
- apps/2CD/concert/backend/src/models/user.model.ts
- apps/2CD/concert/backend/src/resolvers/mutations/index.ts
- apps/2CD/concert/backend/src/resolvers/mutations/request/index.ts
- apps/2CD/concert/backend/src/resolvers/mutations/request/update-request.ts
- apps/2CD/concert/backend/src/resolvers/mutations/user/index.ts
- apps/2CD/concert/backend/src/resolvers/mutations/user/update-password.ts
- apps/2CD/concert/backend/src/resolvers/mutations/user/update-user.ts
- apps/2CD/concert/backend/src/schemas/requist.schema.ts
- apps/2CD/concert/backend/src/schemas/user.schema.ts
- apps/2CD/concert/backend/src/zodSchemas/user.zod.ts
implemented
-updatePassword
-updateUserInfo
-updateRequest 
all mutation tested
> [SERVICE:concert] add user info update mutations,update req mutation

- apps/2CD/hotel/backend/project.json
- apps/2CD/hotel/frontend/cypress/tsconfig.json
- apps/2CD/hotel/frontend/cypress/utils/all-pages.json
- apps/2CD/hotel/frontend/src/app/homeTest/_components/hotel-card.tsx
- apps/2CD/hotel/frontend/src/app/homeTest/page.tsx
- apps/2CD/hotel/frontend/src/graphql/all.graphql
1. backed project json bug fix
2. add hotel card
> feat(hotel): hotel card

- apps/2CD/tinder/backend/specs/resolvers/clerk.spec.ts
- apps/2CD/tinder/backend/src/pages/api/webhooks/clerk.ts
changes on export function ( to default export )
> fix: clerk webhook function fix

- apps/2CD/restaurant/backend/specs/resolvers/mutations/otp/sendOtp.spec.ts
- apps/2CD/restaurant/backend/src/models/otp-model.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/index.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/otp/send-otp.ts
- apps/2CD/restaurant/backend/src/resolvers/mutations/user/change-email.ts
- apps/2CD/restaurant/backend/src/schemas/index.ts
- apps/2CD/restaurant/backend/src/schemas/otp-schema.ts
- apps/2CD/restaurant/backend/src/schemas/user.schema.ts
> feat(restaurant backend): send otp

- apps/2CD/hotel/backend/specs/resolvers/queries/booking/get-all-bookings.spec.ts
- apps/2CD/hotel/backend/specs/resolvers/queries/room/get-all-rooms.spec.ts
- apps/2CD/hotel/backend/src/resolvers/queries/booking/get-all-booking.ts
- apps/2CD/hotel/backend/src/resolvers/queries/room/get-all-rooms.ts
- apps/2CD/hotel/backend/src/schemas/booking.schema.ts
1.get-all-room query add populate
2.get-all-booking add populate
3.change get-all-room test
4.change get-all-booking test
> perf(hotel): add get-all-room and get-all-booking populate

- apps/2CD/hotel/backend/src/models/hotel.ts
- apps/2CD/hotel/backend/src/models/review.ts
1.added image on hotel model 
2.review max star change 5 to 10
> feat(added image on hotel model): small changes

- apps/2CD/hotel/frontend/src/app/details/[id]/page.tsx
- apps/2CD/hotel/frontend/src/app/details/_components/Description.tsx
- apps/2CD/hotel/frontend/src/app/details/_components/HotelImage.tsx
- apps/2CD/hotel/frontend/src/app/details/_components/HotelLocation.tsx
- apps/2CD/hotel/frontend/src/app/details/_components/PriceDetail.tsx
- apps/2CD/hotel/frontend/src/app/details/_components/Skeleton.tsx
- apps/2CD/hotel/frontend/src/graphql/all.graphql
> feat(add details): add

- apps/2CD/tinder/backend/specs/resolvers/queries/user/get-all-users.spec.ts
- apps/2CD/tinder/backend/specs/resolvers/queries/user/me.spec.ts
- apps/2CD/tinder/backend/src/resolvers/index.ts
- apps/2CD/tinder/backend/src/resolvers/queries/user/get-all-users.ts
- apps/2CD/tinder/backend/src/resolvers/queries/user/me.ts
- apps/2CD/tinder/backend/src/schemas/user.schema.ts
Queries
- get user by clerkid
- get all user
-
> feat: added query (get user by clerid), (get all user data)

- apps/2CD/restaurant/frontend/cypress/utils/all-pages.json
- apps/2CD/restaurant/frontend/src/app/admin/_components/MenuBar.tsx
- apps/2CD/restaurant/frontend/src/app/admin/page.tsx
created admin page and admin page menu-bar
> feat(restaurant-frontend): admin-page setup

- apps/2CD/tinder/backend/specs/resolvers/queries/user/get-all-users.spec.ts
- apps/2CD/tinder/backend/specs/resolvers/queries/user/me.spec.ts
- apps/2CD/tinder/backend/src/resolvers/queries/user/get-all-users.ts
- apps/2CD/tinder/backend/src/resolvers/queries/user/me.ts
- apps/2CD/tinder/backend/src/schemas/profile.schema.ts
- apps/2CD/tinder/backend/src/schemas/user.schema.ts
User schema changes
added relations
- profile, matches, likesFrom, likesTo, messages
Get all users, get user by id
added relations
- profile, matches, likesFrom, likesTo, messages
> fix: fixes on get-user-by-id get-all-user

- apps/2CD/hotel/backend/specs/resolvers/queries/booking/most-booked-hotel.spec.ts
- apps/2CD/hotel/backend/src/models/booking.ts
- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/backend/src/resolvers/queries/booking/most-booked-hotel.ts
- apps/2CD/hotel/backend/src/schemas/booking.schema.ts
1. add most-booking-hotel in resolver
2. add most-booking-hotel test
> feat(hotel): get most booking hotel in resolver

- apps/2CD/tinder/backend/next.config.js
- apps/2CD/tinder/backend/src/app/api/graphql/route.ts
- apps/2CD/tinder/frontend/next.config.js
- apps/2CD/tinder/frontend/src/app/layout.tsx
- apps/2CD/tinder/frontend/src/app/page.tsx
- apps/2CD/tinder/frontend/src/components/providers/ApolloWrapper.tsx
- adjusted router.ts file to fix cors issue
- changed appollowrapper file which made entire page appear white
- uploaded loading component
> fix(client): white screen error connected with apollo wrapper file

- apps/2CD/concert/backend/specs/resolvers/queries/concert/get-featured-concerts.spec.ts
- apps/2CD/concert/backend/src/resolvers/queries/concert/get-featured-concerts.ts
- apps/2CD/concert/backend/src/resolvers/queries/concert/index.ts
- apps/2CD/concert/backend/src/schemas/concert.schema.ts
added:
-getFeaturedConcerts query
-getFeaturedConcerts test
changed file:
-concertSchema
> feat(concert:backend): added getFeaturedConcerts query

- apps/2CD/concert/frontend/cypress/e2e/(admin)/ticket-page.cy.tsx
- apps/2CD/concert/frontend/src/app/(admin)/ticket/page.tsx
1. concert search filter e2e test hiisen
> test(concert-frontend): concert search filter e2e test

- apps/2CD/hotel/backend/src/resolvers/index.ts
- apps/2CD/hotel/frontend/cypress/utils/all-pages.json
- apps/2CD/hotel/frontend/src/app/page.tsx
- apps/2CD/hotel/frontend/src/components/hotel/hotel-card.tsx
- apps/2CD/hotel/frontend/src/components/hotel/most-booked-hotel.tsx
- apps/2CD/hotel/frontend/src/components/hotel/popular-hotel.tsx
- apps/2CD/hotel/frontend/src/graphql/all.graphql
1.add popular hotel and most booked hotel in homePage
> feat(hotel): update popular hotel and most booked hotel in homePage

- apps/2FH/hotelbooking/backend/specs/resolvers/mutations/booking/create-book.spec.ts
- apps/2FH/hotelbooking/backend/src/resolvers/mutations/booking/create-book.ts
- apps/2FH/hotelbooking/backend/src/schemas/booking.schema.ts
- apps/2FH/hotelbooking/frontend/src/components/payment/_components/BookingPayment.tsx
Create booking backend  return response.booking
> Create booking back end bug fixed
